const FESTIVAL_START_MONTH = '01';
const FESTIVAL_START_DAY = '23';
const FESTIVAL_END_MONTH = '02';
const FESTIVAL_END_DAY = '01';
const FESTIVAL_YEAR = '2020';

const START_DATE = new Date(`${FESTIVAL_YEAR}-${FESTIVAL_START_MONTH}-${FESTIVAL_START_DAY}`);
const END_DATE = new Date(`${FESTIVAL_YEAR}-${FESTIVAL_END_MONTH}-${FESTIVAL_END_DAY}`);

module.exports = {
  FESTIVAL_START_MONTH,
  FESTIVAL_START_DAY,
  FESTIVAL_END_MONTH,
  FESTIVAL_END_DAY,
  FESTIVAL_YEAR,
  START_DATE,
  END_DATE
};
